services:
  - type: web
    name: face-recognition-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "face_detection.py"
    envVars:
      - key: PYTHON_HOST
        value: 0.0.0.0
      - key: PYTHON_PORT
        value: 10000
      - key: SPRINGBOOT_API_URL
        value: https://your-springboot-api-url.com
      - key: IMAGE_SAVE_PATH
        value: ./temp_images
    plan: free
